package main

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	inferenceTokens = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "jetweb_inference_tokens_total",
		Help: "Total tokens generated by inference models",
	})

	walMutations = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "jetweb_wal_mutations_total",
		Help: "Total WAL mutations",
	})

	driftEvents = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "jetweb_drift_events_total",
		Help: "Total drift events detected",
	})

	consensusLatency = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "jetweb_consensus_latency_ms",
		Help: "Average consensus decision latency",
	})

	arbitrationTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "jetweb_arbitration_total",
		Help: "Total arbitration escalations",
	})
)

func InitPrometheus() {
	prometheus.MustRegister(inferenceTokens)
	prometheus.MustRegister(walMutations)
	prometheus.MustRegister(driftEvents)
	prometheus.MustRegister(consensusLatency)
	prometheus.MustRegister(arbitrationTotal)

	http.Handle("/metrics", promhttp.Handler())
}
