// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: swarm/proto/gemini_handshake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_swarm_proto_gemini_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_gemini_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_gemini_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HandshakeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    string                 `protobuf:"bytes,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_swarm_proto_gemini_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_gemini_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_gemini_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *HandshakeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_swarm_proto_gemini_handshake_proto protoreflect.FileDescriptor

const file_swarm_proto_gemini_handshake_proto_rawDesc = "" +
	"\n" +
	"\"swarm/proto/gemini_handshake.proto\x12\x06gshell\"I\n" +
	"\x10HandshakeRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x11HandshakeResponse\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\tR\n" +
	"receiverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2Q\n" +
	"\rGeminiService\x12@\n" +
	"\tHandshake\x12\x18.gshell.HandshakeRequest\x1a\x19.gshell.HandshakeResponseB Z\x1epqr.info/mev/swarm/proto;protob\x06proto3"

var (
	file_swarm_proto_gemini_handshake_proto_rawDescOnce sync.Once
	file_swarm_proto_gemini_handshake_proto_rawDescData []byte
)

func file_swarm_proto_gemini_handshake_proto_rawDescGZIP() []byte {
	file_swarm_proto_gemini_handshake_proto_rawDescOnce.Do(func() {
		file_swarm_proto_gemini_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_proto_gemini_handshake_proto_rawDesc), len(file_swarm_proto_gemini_handshake_proto_rawDesc)))
	})
	return file_swarm_proto_gemini_handshake_proto_rawDescData
}

var file_swarm_proto_gemini_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_swarm_proto_gemini_handshake_proto_goTypes = []any{
	(*HandshakeRequest)(nil),  // 0: gshell.HandshakeRequest
	(*HandshakeResponse)(nil), // 1: gshell.HandshakeResponse
}
var file_swarm_proto_gemini_handshake_proto_depIdxs = []int32{
	0, // 0: gshell.GeminiService.Handshake:input_type -> gshell.HandshakeRequest
	1, // 1: gshell.GeminiService.Handshake:output_type -> gshell.HandshakeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swarm_proto_gemini_handshake_proto_init() }
func file_swarm_proto_gemini_handshake_proto_init() {
	if File_swarm_proto_gemini_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_proto_gemini_handshake_proto_rawDesc), len(file_swarm_proto_gemini_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swarm_proto_gemini_handshake_proto_goTypes,
		DependencyIndexes: file_swarm_proto_gemini_handshake_proto_depIdxs,
		MessageInfos:      file_swarm_proto_gemini_handshake_proto_msgTypes,
	}.Build()
	File_swarm_proto_gemini_handshake_proto = out.File
	file_swarm_proto_gemini_handshake_proto_goTypes = nil
	file_swarm_proto_gemini_handshake_proto_depIdxs = nil
}
