// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: swarm/proto/gemini_handshake.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeminiService_Handshake_FullMethodName = "/gshell.GeminiService/Handshake"
)

// GeminiServiceClient is the client API for GeminiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeminiServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type geminiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeminiServiceClient(cc grpc.ClientConnInterface) GeminiServiceClient {
	return &geminiServiceClient{cc}
}

func (c *geminiServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, GeminiService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeminiServiceServer is the server API for GeminiService service.
// All implementations must embed UnimplementedGeminiServiceServer
// for forward compatibility.
type GeminiServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	mustEmbedUnimplementedGeminiServiceServer()
}

// UnimplementedGeminiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeminiServiceServer struct{}

func (UnimplementedGeminiServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedGeminiServiceServer) mustEmbedUnimplementedGeminiServiceServer() {}
func (UnimplementedGeminiServiceServer) testEmbeddedByValue()                       {}

// UnsafeGeminiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeminiServiceServer will
// result in compilation errors.
type UnsafeGeminiServiceServer interface {
	mustEmbedUnimplementedGeminiServiceServer()
}

func RegisterGeminiServiceServer(s grpc.ServiceRegistrar, srv GeminiServiceServer) {
	// If the following call panics, it indicates UnimplementedGeminiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeminiService_ServiceDesc, srv)
}

func _GeminiService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeminiServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeminiService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeminiServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeminiService_ServiceDesc is the grpc.ServiceDesc for GeminiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeminiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gshell.GeminiService",
	HandlerType: (*GeminiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _GeminiService_Handshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swarm/proto/gemini_handshake.proto",
}
